// this is your main.js script
let challenge = "30 Days Of JavaScript"
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substr(0,2))
console.log(challenge.substring(3,22))
console.log(challenge.includes('Script'))
console.log(challenge.split())
console.log(challenge.split(' '))
console.log('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(','))
console.log(challenge.replace('JavaScript','Python'))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt(challenge.charAt(11)))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
console.log('You cannot end a sentence with because because because is a conjunction'.indexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.lastIndexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.search('because'))
console.log(' 30 Days Of JavaScript '.trim(' '))
console.log(challenge.startsWith('3'))
console.log(challenge.endsWith('t'))
console.log(challenge.match(/a/g))
console.log(challenge.substr(0,10).concat(' JavaScript'))
console.log(challenge.repeat(2))
console.log("The quote 'There is no exercise better for the heart than reaching down and lifting people up.' by John Holmes teaches us to help one another.")
console.log("Love is not patronizing and charity isn't about pity, it is about love. Charity and love are the same -- with charity you give love, so don't just give money but reach out your hand instead.")
console.log(typeof parseInt('10') == typeof 10)
console.log(Math.round(parseFloat('9.8')) == 10)
console.log('python'.includes('on'))
console.log('jargon'.includes('on'))
console.log('I hope this course is not full of jargon.'.includes('jargon'))
console.log(Math.floor(Math.random()*110))
console.log(Math.floor(Math.random()*51+50))
console.log(Math.floor(Math.random()*256))
let js = 'JavaScript'
randInt = Math.random()*js.length
console.log(js.charAt(randInt))
let a = ' 1'
console.log(a.repeat(5))